on: 
  push:
    branches:
     - main
     
name: 🚀 Deploy Produção
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Sincronizando
      uses: actions/checkout@v3
    
    - name: Deploy Finalizado
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: 50.116.86.134
        username: mercado@scsport.com.br
        password: C0mpany!SC10