on: 
  push:
    branches:
     - main
     
name: 🚀 Deploy Produção
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Sincronizando
      uses: actions/checkout@v3
    
    - name: Deploy Finalizado
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME_PRODUCAO }}
        password: ${{ secrets.PASSWORD_PRODUCAO }}